# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on WIN MSVC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CTEST_OUTPUT_ON_FAILURE: "true"
  CMAKE_BUILD_TYPE: "Release"

jobs:
  build:
    name: Windows Latest MSVC
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'  # 确保检出子模块

    - name: Set up MSVC
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -S . -B build -DCMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}}

    - name: Build
      run: cmake --build build --config ${{env.CMAKE_BUILD_TYPE}}

    - name: Test
      working-directory: build
      run: ctest --output-on-failure -C ${{env.CMAKE_BUILD_TYPE}} 